### ISSUE TITLE
sys-devel/bison-2.7.1-r2 EAPI 6

### ISSUE THREAD

**Issue by lourdas** [stefantalpalaru/gentoo-overlay#154]
I get this error after syncing with your overlay:

    Calculating dependencies        9 * ERROR: sys-devel/bison-2.7.1-r2::stefantalpalaru failed (depend phase):
    *   flag-o-matic: EAPI 6 not supported
    * 
    * Call stack:
    *               ebuild.sh, line 632:  Called source '/var/db/repos/stefantalpalaru/sys-devel/bison/bison-2.7.1-r2.ebuild'
    *   bison-2.7.1-r2.ebuild, line   6:  Called inherit 'flag-o-matic'
    *               ebuild.sh, line 312:  Called __qa_source '/var/db/repos/gentoo/eclass/flag-o-matic.eclass'
    *               ebuild.sh, line 123:  Called source '/var/db/repos/gentoo/eclass/flag-o-matic.eclass'
    *     flag-o-matic.eclass, line  18:  Called die
    * The specific snippet of code:
    *   	*) die "${ECLASS}: EAPI ${EAPI:-0} not supported" ;;
    * 
    * If you need support, post the output of `emerge --info '=sys-devel/bison-2.7.1-r2::stefantalpalaru'`,
    * the complete build log and the output of `emerge -pqv '=sys-devel/bison-2.7.1-r2::stefantalpalaru'`.
    * Working directory: '/usr/lib/python3.12/site-packages'
    * S: '/var/tmp/portage/sys-devel/bison-2.7.1-r2/work/bison-2.7.1'

**Comment by stefantalpalaru** [comment]
You did not manage to sync my overlay properly, because the latest version of that package is 2.7.1-r3 and it uses "EAPI=8": https://github.com/stefantalpalaru/gentoo-overlay/blob/b520b56eadf0716d78622ee2d22be24934b6bc63/sys-devel/bison/bison-2.7.1-r3.ebuild#L4

What's the output of `emaint sync --repo stefantalpalaru` ?

**Comment by lourdas** [comment]
It syncs ok:

    emaint sync --repo stefantalpalaru
    >>> Syncing repository 'stefantalpalaru' into '/var/db/repos/stefantalpalaru'...
    /usr/bin/git fetch origin --depth 2
    remote: Total 0 (delta 0), reused 0 (delta 0), pack-reused 0 (from 0)
    /usr/bin/git reset --merge refs/remotes/origin/master
    === Sync completed for stefantalpalaru

    Action: sync for repo: stefantalpalaru, returned code = 0

**Comment by lourdas** [comment]
I get this error in two different machines using the repository.

**Comment by stefantalpalaru** [comment]
What is the output of this command?

`git -C /var/db/repos/stefantalpalaru remote -vv`

**Comment by lourdas** [comment]
origin	https://github.com/gentoo-mirror/stefantalpalaru.git (fetch)
    origin	https://github.com/gentoo-mirror/stefantalpalaru.git (push)

**Comment by stefantalpalaru** [comment]
OK. What happened here is that my overlay was removed from the official list, [on July 21](https://github.com/gentoo/api-gentoo-org/commit/7c46900a7c4cd57b11091ae8327a1e855bb97762), and that overlay mirror used by eselect-repository stopped updating.

The fix is to delete and re-add my overlay, on all your machines:

```text
eselect repository remove stefantalpalaru
eselect repository add stefantalpalaru git https://github.com/stefantalpalaru/gentoo-overlay
emaint sync --repo stefantalpalaru
```

**Comment by lourdas** [comment]
Yes, that worked. Thanks!
