### ISSUE TITLE
Gentoo Overlay Stefantalpalaru

### ISSUE THREAD

**Issue by rafaelzigx** [stefantalpalaru/gentoo-overlay#32]
Hello there,

When syncing your overlay, I always see this message:
Unavailable repository 'science' referenced by masters entry in '/var/lib/layman/stefantalpalaru/metadata/layout.conf'

Perhaps you're already aware but, just in case you're not.

Cheers.

**Comment by stefantalpalaru** [comment]
That's because I just added the "science" overlay as a master, when I added a newer version of "sci-libs/openblas". I need this to be able to check the ebuilds with `repoman`.

If you're bothered by that message, you can always add the "science" overlay and go through their BLAS and LAPACK migration procedure: https://github.com/gentoo/sci

It's not actually needed. You can just ignore the message and carry on as before.

**Comment by stefantalpalaru** [comment]
I documented this in README.md.
