### ISSUE TITLE
gnome-base/dconf-0.30.1:0 conflicts with <gnome-base/dconf-0.30.1 required by (app-emulation/vmware-workstation-15.0.4.12990004:0/0::stefantalpalaru, installed)

### ISSUE THREAD

**Issue by lourdas** [stefantalpalaru/gentoo-overlay#37]
I get this error while emerging world:

    (gnome-base/dconf-0.30.1:0/0::gentoo, ebuild scheduled for merge) conflicts with
    <gnome-base/dconf-0.30.1 required by (app-emulation/vmware-workstation-15.0.4.12990004:0/0::stefantalpalaru, installed)

Should the dependency for dconf raise?

**Comment by dpaessler** [comment]
I have gnome-base/dconf-0.32.0 from gnome-next overlay and can confirm that it works fine.

Additionally there is a slot for sys-fs/fuse version 2 (sys-fs/fuse:0), which is needed for vmware-workstation. On my system, version 3 is needed (slot sys-fs/fuse:3) for gnome-base/gvfs-1.41.1, so the ebuild for vmware-workstation should depend on slot sys-fs/fuse:0 instead of just sys-fs/fuse

**Comment by stefantalpalaru** [comment]
Fixed. Thank you for reporting it.
