### ISSUE TITLE
app-emulation/vmware-workstation fails in install stage

### ISSUE THREAD

**Issue by yvesh** [stefantalpalaru/gentoo-overlay#97]
Hi,
emerging vmware-workstation (actually this time not the modules) fails:

```
>>> Install app-emulation/vmware-workstation-16.2.1.18811642 into /var/tmp/portage/app-emulation/vmware-workstation-16.2.1.18811642/image
chmod: cannot access '/var/tmp/portage/app-emulation/vmware-workstation-16.2.1.18811642/image/opt/vmware/lib/vmware/bin/*': No such file or directory
 * ERROR: app-emulation/vmware-workstation-16.2.1.18811642::stefantalpalaru failed (install phase):
 *   fperms failed
```

The folder is existing (/var/tmp/portage/app-emulation/vmware-workstation-16.2.1.18811642/image/opt/vmware/lib/vmware/bin/).

Any ideas?

Thanks,
Yves

**Comment by stefantalpalaru** [comment]
What's the output of `emerge -pv vmware-workstation`?

**Comment by yvesh** [comment]
```
#  emerge -pv vmware-workstation

These are the packages that would be merged, in order:

Calculating dependencies... done!
[ebuild  N    #] app-emulation/vmware-workstation-16.2.1.18811642::stefantalpalaru  USE="cups macos-guests modules systemd vmware-tools-linux vmware-tools-windows -doc -ovftool -vix -vmware-tools-darwin -vmware-tools-darwinPre15 -vmware-tools-linuxPreGlibc25 -vmware-tools-netware -vmware-tools-solaris -vmware-tools-winPre2k -vmware-tools-winPreVista" 0 KiB

Total: 1 package (1 new), Size of downloads: 0 KiB
```

**Comment by stefantalpalaru** [comment]
Fixed. Thanks for reporting it!

The bug was an interesting one: `fperms 0755 "${VM_INSTALL_DIR}"/lib/vmware/bin/*` does that file globbing before prefixing the path with "${ED}", so straight from the root fs, which obviously fails the first time you install the package.

I was only able to replicate this after uninstalling vmware-workstation and then trying to install it again.
